### ISSUE TITLE
[FEATURE] Set Up Database

### ISSUE THREAD

**Issue by kai-franke** [kai-franke/yummy-rater#1]
## Value proposition
As a developer
I want set up a database to store relevant information
so that the app can manage my data efficiently.
## Description
Design and implement a MongoDB database schema that ensures it supports the application's requirements. The schema should be flexible, scalable, and optimized for performance, ensuring efficient data management.

**User Document Schema:**
```
{
  "_id": ObjectId("..."),
  "provider_id": "78946523",
  "first_name": "John",
  "last_name": "Doe",
  "profile_image": "path/to/profile_image.jpg",
  "email": "john.doe@example.com",
  "products": [
    {
      "product_id": ObjectId("..."),
      "ean": 12345678,
      "name": "Product Name",
      "brand": "Brand Name",
      "description": "Product description",
      "image": "path/to/product_image.jpg",
      "date_added": ISODate("2023-01-01T00:00:00Z"),
      "user_rating": 4,
      "user_note": "This is a great product."
    },
    {
      "product_id": ObjectId("..."),
      "ean": 12345678,
      "name": "Another Product",
      "brand": "Another Brand",
      "description": "Another product description",
      "image": "path/to/another_product_image.jpg",
      "date_added": ISODate("2023-02-01T00:00:00Z"),
      "user_rating": 5,
      "user_note": "This product is even better."
    },
  ]
}
```

```

```
## Acceptance criteria
- [x] The MongoDB database is set up and configured.
- [x] The database schema supports all specified application requirements.
- [x] The collection is created as per the schema design.
- [x] Data is correctly collected and stored when the API is called.
## Tasks
- [x] Create new feature branch
- [x] Set up the collection in MongoDB
- [x] Add dummy data to the collection
- [x] Add mongoose to project
- [x] Connect database (create dbConnect.jsx)
- [x] Build the mongoose schema and model
- [x] Create the API endpoint to interact with the database
- [x] Test the database setup and API integration
- [x] Merge the feature branch after review and approval

**Comment by kai-franke** [comment]
Do we need a field for authentication?
