### ISSUE TITLE
[FEATURE] User Registration and Login

### ISSUE THREAD

**Issue by kai-franke** [kai-franke/yummy-rater#10]
## Value proposition
As a user
I want to register and log in
In order to save my personal settings and product ratings, and associate them with my account.
## Description
- Scribble / design or text
- Precise, no unnecessary information
## Acceptance criteria
- [ ] The homepage asks to login
- [ ] No part of the app is available without login
- [ ] It is possible to login with github
## Tasks
- [x] Create new feature branch
- [x] install next-auth
- [x] create `pages/api/auth/[...nextauth].js
- [x] create a Login component
- [x] render the Login component in `pages/index.tsx`
- [x] create a Auth Component that requires a session to render its children
- [x] in _app.tsx wrap the Auth component around the app.
