### ISSUE TITLE
[FEATURE] Implement Product Search Functionality

### ISSUE THREAD

**Issue by kai-franke** [kai-franke/yummy-rater#11]
## Value proposition
As a user
I want a search function that allows me to search for a specific product within the "My products" page by name or EAN
In order to see my rating and comment for this product.
## Description
-
## Acceptance criteria
- [ ] Within the header of or above the product table is an input field for entering the search term shown.
- [ ] Upon entering something into the search field, the list is reduced to the corresponding search results. The search process doesn't need a confirmation, it is searched whenever the input changes.
- [ ] Brand, Product Name, User Comment and EAN fields will be searched for the entered search term.
- [ ] The search results allow for variations and deviations in spelling, e.g. the search term "tost" should also return a product "toast"
## Tasks
- [ ] Create new feature branch
- [ ] Implement fuzzy search (fuse.js)
- [ ] Check if https://mui.com/x/react-data-grid/filtering/quick-filter/ could be an option as well

**Comment by kai-franke** [comment]
Es gibt eine Suche (https://mui.com/x/react-data-grid/filtering/quick-filter/)
