### ISSUE TITLE
[FEATURE] View Saved Products and Ratings

### ISSUE THREAD

**Issue by kai-franke** [kai-franke/yummy-rater#12]
## Value proposition
As a user
I want to view a list of all the products I have saved and rated
In order to easily manage and access my favorite products and their ratings.
## Description
- 
## Acceptance criteria
- [x] The "Search" page is renamed "My Products"
- [x] The "My Products" page displays a Table or a List that shows all saved products in rows (columns needes: Thumbnail-Image, Product Name, Brand, Rating, User Comment)
- [x] Newest entries are shown on top of the list.
- [x] Clicking a single Product (row) opens a modal, displaying the Card component filled with all corresponding product information
- [x] Optional: If the used component for the table offers this functionality, each column can be sorted.
## Tasks
- [x] Create new feature branch
- [x] Check if a MUI List, Table or Data Grid is the sufficient component (https://mui.com/x/react-data-grid/)
- [x] Map and render product data
- [x] Make use of existing Modal and Card component

**Comment by kai-franke** [comment]
- Übersichtseite "My Products"
- Verwendet MUI Komponente Data-Grid (https://mui.com/x/react-data-grid/)
- Listet alle gespeicherten Producte auf
- Bietet die Möglichkeit Produkte zu löschen oder editieren (ggf. direkt in der Liste oder link zu Details-Seite)
- Ggf. können Note und Rating direkt in der Liste geändert werden
- Einträge können gefiltert werden (Column Filter)
- Es gibt eine Suche (https://mui.com/x/react-data-grid/filtering/quick-filter/)
