### ISSUE TITLE
[FEATURE] Create Home Page with Header

### ISSUE THREAD

**Issue by kai-franke** [kai-franke/yummy-rater#2]
## Value proposition
As a user
I want to see a home page with a header that displays the app name
In order to easily know which app I am using.
## Description
The home page of the application should have a header component that prominently displays the name of the app. The app name should be displayed in a way that is clear and prominent.

<img src="https://github.com/user-attachments/assets/89e97cbb-e1a1-4b19-9653-f58594edf1ae" width="300" />

## Acceptance criteria
- [x] The home page is shown, when the app is started.
- [x] The home page should have a header component at the top.
- [x] The header should display the app name.
- [x] The page should have a headline "Home".
- [x] All used components are from Material UI.
- [x] The header should be responsive and maintain its design across different screen sizes.
- [x] The app name in the header should be accessible and have appropriate ARIA labels.
- [x] Ensure the header background color and text color have sufficient contrast for readability.
## Tasks
- [x] Create a new feature branch named **feature/header-component**.
- [x] Set up the header component using Material UI's AppBar and Typography components.
- [x] Implement the styling and ensure it is responsive.
- [x] Add ARIA labels to the header component for accessibility.
- [x] Ensure the header component passes accessibility checks.
- [ ] Perform a code review and merge the feature branch into the main branch.
