### ISSUE TITLE
[FEATURE] Create Product Details Page

### ISSUE THREAD

**Issue by kai-franke** [kai-franke/yummy-rater#5]
## Value proposition
As a user
I want a product details page that shows information such as product image, name, brand, description, EAN, and rating
In order to get detailed information about a product.
## Description
<img src="https://github.com/user-attachments/assets/9ead8b84-bb6b-482c-88de-0850f58fda98" width="300" />

The API call functionality for fetching product information will be implemented in a future task.
This dummy data can be used:
```
const dummyProducts = [
  {
    ean: 4000417601810,
    name: "Ritter Sport Alpenmilch Schokolade",
    brand: "Ritter Sport",
    description:
      "Alpen-Vollmilchschokolade with a minimum of 30% cocoa content. Creamy milk chocolate made from the finest Alpine milk.",
    image:
      "https://images.openfoodfacts.org/images/products/400/041/760/1810/front_de.6.400.jpg",
    user_rating: 4.5,
    user_note:
      "A delicious and smooth milk chocolate, perfect for a sweet treat. The texture is creamy, and the cocoa flavor is rich without being too overpowering.",
  },
  {
    ean: 4071800001098,
    name: "Buttertoastbrot",
    brand: "Brotland",
    description:
      "Soft and light butter toast bread, perfect for breakfast or snacks. Contains wheat flour, natural sourdough, and butterfat for a rich and satisfying taste.",
    image:
      "https://images.openfoodfacts.org/images/products/407/180/000/1098/front_de.15.400.jpg",
    user_rating: 3.2,
    user_note:
      "Delicious and fluffy toast bread. It has a nice buttery flavor and toasts evenly. Ideal for sandwiches or just with a spread.",
  },
  {
    ean: 3057640186158,
    name: "Volvic - Natürliches Mineralwasser",
    brand: "Volvic",
    description:
      "Natürliches Mineralwasser ohne Kohlensäure. Ideal für den täglichen Wassergenuss.",
    image:
      "https://images.openfoodfacts.org/images/products/305/764/018/6158/front_de.38.400.jpg",
    user_rating: 4,
    user_note:
      "Erfrischendes Wasser, das sich hervorragend für den täglichen Konsum eignet. Die Qualität und der Geschmack sind sehr gut.",
  },
  {
    ean: 40804644,
    name: "Gewürzgurken",
    brand: "Kühne",
    description:
      "Crispy pickled cucumbers in a tangy vinegar brine, perfect for sandwiches and snacks.",
    image:
      "https://images.openfoodfacts.org/images/products/40804644/front_en.23.400.jpg",
    user_rating: 1.8,
    user_note:
      "An addition to any sandwich! The pickles are crunchy but not flavorful.",
  },
];
```

## Acceptance criteria
- [x] The product details page should visually resemble the provided mockup, including the layout and elements.
- [x] The page should include the following elements:
  - A product image.
  - A rating system with stars, allowing for half-star ratings.
  - Product brand name displayed in a smaller font and colored (as in the mockup).
  - Product name in a bold, larger font.
  - A note section.
  - Product details such as EAN and the date it was added.
  - A "Close" button at the bottom of the page for future use.
- [x] The page should be responsive and maintain its design across various screen sizes (e.g., mobile, tablet, desktop).
- [x] Dummy data for at least three products should be used to test the layout and functionality.
- [x] The page should be integrated into the main app with proper navigation.

## Tasks
- [x] Create new feature branch
- [x] Set up the basic structure and layout of the product details page to match the provided mockup.
  - Use **Card** and **CardContent** components for the main container of the product details.
  - Use **CardMedia** for the product image placeholder.
  - Use **Typography** for displaying the product name, brand, and additional text (e.g., note, EAN, added date).
  - Use **Rating** component for the star rating system, ensuring that half-star ratings are supported.
  - Use **Button** component for the "Close" button.
- [x] Implement the rating system with the ability to display half-star ratings.
- [x] Add dummy data for at least three products, including product image, name, brand, description, EAN, and rating.
- [x] Ensure the page is responsive and tested on different screen sizes.
- [ ] Submit a pull request for review and merge.
