### ISSUE TITLE
[FEATURE] Create Add New Product Page

### ISSUE THREAD

**Issue by kai-franke** [kai-franke/yummy-rater#6]
## Value proposition
As a registered user
I want to add new products to the database by entering EAN, name, brand, product image, note, and rating
In order to review this information in future use of the app.

## Description
The "Add Product" page allows registered users to input detailed information about new products. The input of the EAN is only possible via scanning a product's barcode.

Below is a visual representation of the page layout:
<img src="https://github.com/user-attachments/assets/9bb8a537-34d4-4fd0-8ad6-6240e44f231d" width="300" />

## Acceptance criteria
- [x] The `add` page should have a headline "Add Product".
- [x] The page must display input fields for:
  - EAN (auto-filled and non-editable)
  - Product Name (required)
  - Product Brand
  - Product Image (URL only, optional)
  - Note (optional, up to 500 characters)
  - Rating (required, 0-5 stars, allowing half stars)
- [x] Above the form is a "Scan" button that gets its functionality later.
- [x] If no image URL is provided or the image URL is invalid, the product should display a placeholder image on the product details page.
- [x] The "Add Product" button is enabled only when all required fields are valid and completed.
- [ ] The form should display a loading indicator (loading spinner) during submission.
- [x] Upon successful submission, the product must be saved to the MongoDB database in the user's products array.
- [x] After successful submission, redirect the user to the product details page for the newly added product.
- [ ] In case of an error, display a meaningful error message.
- [x] The form must be responsive across devices.
- [x] Image upload functionality is optional; the form can be successfully submitted without uploading an image.
- [x] All used components are from Material UI.

## Tasks
- [ ] Create new feature branch **feature/new-product-page**
- [ ] Implement the service to handle product addition to the user's products array in MongoDB.
- [ ] Use MUI `TextField` components for EAN, Brand Name, Product Name, and Note.
- [ ] Add a MUI `Rating` component for user star rating (0-5 stars, half stars allowed).
- [ ] Develop the logic to handle form submission, calling the MongoDB service to add the product to the database.
- [ ] Display a loading spinner using MUI `Progress` component during form submission.
- [ ] After a successful submission, redirect the user to the newly added product's detail page.
- [ ] On error (validation or server), display an error message below the submit button (please check MUI `Alert` component).
- [ ] Organize the form using MUI `Grid` and `Paper` components for clean and responsive design across different devices.
- [ ] Ensure the page passes accessibility checks.
- [ ] Perform a code review and merge the feature branch into the main branch
